services:
  backend:
    build: ./backend
    container_name: cae-etm-backend
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=minha-chave-secreta-accenture-ka-123
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
    networks:
      - cae-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/auth/login", "||", "exit", "1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build: ./frontend
    container_name: cae-etm-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - cae-network
    restart: unless-stopped

networks:
  cae-network:
    driver: bridge
