services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=minha-chave-secreta-accenture-ka-123
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
    restart: unless-stopped
